### ISSUE TITLE
Change sounds 

### ISSUE THREAD

**Issue by BramBleys** [BramBleys/FlinkSpreken#21]
Luister goed:
![image](https://user-images.githubusercontent.com/33414465/49699147-f3af0080-fbcd-11e8-9540-d698576f4e3d.png)

Hondje waf:
![image](https://user-images.githubusercontent.com/33414465/49699146-e2fe8a80-fbcd-11e8-9237-ea6af4e250dd.png)

Zeg het zelf eens:
![image](https://user-images.githubusercontent.com/33414465/49699156-16d9b000-fbce-11e8-80f0-c7451b2970e8.png)

**Comment by BramBleys** [comment]
Hondje waf is done!

**Comment by Fastenakelsk** [comment]
Zeg het zelf eens is done !
Waiting for "Super flink geluisterd!" sound file to finish "Luister Goed"
